[package]
name = "chessclock"
version = "0.1.0"
authors = ["calvicius"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.15.4"
gdk = "0.15.4"
glib = "0.15.10"
